CREATE TABLE IF NOT EXISTS user_roles (
`user_id` VARCHAR(36) NOT NULL,
`role_id` VARCHAR(36) NOT NULL,
`assigned_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (user_id, role_id),
FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE
);