CREATE TABLE IF NOT EXISTS users (
`id` VARCHAR(36) NOT NULL PRIMARY KEY,
`email` VARCHAR(40) NOT NULL,
`name` VARCHAR(40) NOT NULL,
`created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
`updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);